import { writeFileSync, readFileSync, existsSync } from "fs"
import { join } from "path"
import { MEMORY_HOME } from "../store"
import type { Memory } from "../store"

export const HOOKS_SH = join(MEMORY_HOME, "shell-hooks.sh")

// Redirect rules: if memory says "prefer A over B", intercept B commands
const REDIRECT_RULES: Array<{
  category: string
  matchContent: RegExp        // pattern to detect preference in memory content
  winner: RegExp              // extract winner tool name
  intercept: string[]         // commands to intercept
  buildAlias: (winner: string) => string
}> = [
  {
    category:     "packageManager",
    matchContent: /uses (bun|npm|yarn|pnpm) as package manager/i,
    winner:       /uses (\w+) as package manager/i,
    intercept:    ["npm", "yarn", "pnpm"],
    buildAlias: (w) => [
      `npm()  { echo "⚡ memory → ${w}"; command ${w} "$@"; }`,
      `yarn() { echo "⚡ memory → ${w}"; command ${w} "$@"; }`,
      `npx()  { echo "⚡ memory → ${w === "bun" ? "bunx" : w + " exec"}"; command ${w === "bun" ? "bunx" : w} "$@"; }`,
    ].filter(line => {
      // Don't intercept the winner itself
      const intercepted = line.match(/^(\w+)\(\)/)?.[1]
      return intercepted !== w
    }).join("\n"),
  },
]

export function generateShellHooks(memories: Memory[]): string {
  const lines = [
    "# Auto-generated by memory — do not edit manually",
    `# Regenerated: ${new Date().toISOString().slice(0, 10)}`,
    "",
  ]

  for (const rule of REDIRECT_RULES) {
    const mem = memories.find(
      m => m.confidence >= 0.75 && rule.matchContent.test(m.content)
    )
    if (!mem) continue

    const match = mem.content.match(rule.winner)
    if (!match) continue
    const winner = match[1]

    // Don't generate hooks if the winner IS one of the intercepted commands
    // (e.g. npm preferred — no point intercepting npm)
    if (!rule.intercept.includes(winner)) {
      lines.push(`# packageManager: ${winner} (confidence: ${(mem.confidence * 100).toFixed(0)}%)`)
      lines.push(rule.buildAlias(winner))
      lines.push("")
    }
  }

  return lines.join("\n")
}

export function writeShellHooks(memories: Memory[]): void {
  const content = generateShellHooks(memories)
  writeFileSync(HOOKS_SH, content)
}

export function installShellHooks(): { alreadyInstalled: boolean; rcFile: string } {
  const home  = process.env.HOME ?? ""
  const rcFile = existsSync(join(home, ".zshrc"))
    ? join(home, ".zshrc")
    : join(home, ".bashrc")

  const rc      = readFileSync(rcFile, "utf8")
  const marker  = "# memory shell hooks"
  const snippet = `\n${marker}\n[ -f "${HOOKS_SH}" ] && source "${HOOKS_SH}"\n`

  if (rc.includes(marker)) return { alreadyInstalled: true, rcFile }

  writeFileSync(rcFile, rc + snippet)
  return { alreadyInstalled: false, rcFile }
}
